# -*- coding: utf-8 -*-
"""Titanic EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyxOgYw2AM5eiICcg1-zWgFKZGsiyKuc
"""

#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("titanic.csv")
df.head()

# Basic overview
print("=== Info ===")
print(df.info())
print("\n=== Description ===")
print(df.describe())

print("\n=== Missing Values ===")
print(df.isnull().sum())

# Value counts for key categorical variables
print("\n=== Value Counts: Survived ===")
print(df['Survived'].value_counts())

print("\n=== Value Counts: Sex ===")
print(df['Sex'].value_counts())

print("\n=== Value Counts: Pclass ===")
print(df['Pclass'].value_counts())

# Extract Title from Name
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Fill Age with median of Title group
df['Age'] = df.groupby('Title')['Age'].transform(lambda x: x.fillna(x.median()))

# Fill missing Embarked with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Extract Deck from Cabin (first letter)
df['Deck'] = df['Cabin'].astype(str).str[0]

# Drop columns with high missing values or unhelpful
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

# Final missing check
print("\n=== Missing Values After Cleaning ===")
print(df.isnull().sum())

# Plot Survival count
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()
print("Observation: More passengers did not survive (0) than survived (1).")

# Gender distribution
sns.countplot(x='Sex', data=df)
plt.title("Gender Distribution")
plt.show()
print("Observation: There are more male passengers than female passengers.")

# Passenger Class distribution
sns.countplot(x='Pclass', data=df)
plt.title("Passenger Class Distribution")
plt.show()
print("Observation: Most passengers belong to 3rd class, fewer in 1st and 2nd class.")

# Age distribution histogram
df['Age'].plot.hist(bins=30, edgecolor='k')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.show()
print("Observation: Most passengers are between ages 20 and 40.")

# Survival by Gender
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()
print("Observation: Females had a higher survival rate than males.")

# Survival by Class
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()
print("Observation: Passengers in 1st class had higher survival rates compared to 2nd and 3rd classes.")

# Age vs Survival boxplot
sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survival")
plt.show()
print("Observation: Survivors tend to be younger on average, with fewer elderly survivors.")

# Survival by Title
sns.countplot(x='Title', hue='Survived', data=df)
plt.xticks(rotation=45)
plt.title("Survival by Title")
plt.show()
print("Observation: Titles like 'Mrs' and 'Miss' have higher survival counts compared to 'Mr'.")

# Survival by Deck
sns.countplot(x='Deck', hue='Survived', data=df)
plt.title("Survival by Deck")
plt.show()
print("Observation: Passengers on decks B, C, and n show higher survival rates, but many decks have unknown data.")

# Survival by Embarked Port
sns.countplot(x='Embarked', hue='Survived', data=df)
plt.title("Survival by Port of Embarkation")
plt.show()
print("Observation: Passengers who embarked from port 'S' had better survival chances.")

# Correlation heatmap of numeric variables
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
print("Observation: 'Fare' and 'Pclass' are negatively correlated; 'Fare' shows slight positive correlation with 'Survived'.")

# Pairplot of selected numeric columns
sns.pairplot(df[['Age', 'Fare', 'Pclass', 'Survived']], hue='Survived')
plt.suptitle("Pairplot of Age, Fare, Pclass, and Survival", y=1.02)
plt.show()
print("Observation: Survivors tend to pay higher fares and belong more often to 1st class.")

# Scatterplot Age vs Fare colored by Survival
sns.scatterplot(x='Age', y='Fare', hue='Survived', data=df)
plt.title("Age vs Fare by Survival")
plt.show()
print("Observation: Survivors tend to cluster at higher Fare values across ages.")

# Final summary of findings
print("""
Summary of Findings:
- Survival was strongly influenced by gender, with females having a much higher survival rate.
- Passenger class mattered; first-class passengers had better chances of survival than those in lower classes.
- Age also played a role; younger passengers were more likely to survive.
- Titles extracted from names reflected social status, affecting survival chances (e.g., 'Mrs' and 'Miss' had higher survival).
- Deck and embarkation port had some impact, but data missingness limits strong conclusions.
- Fare paid correlated with survival, indicating wealth or class advantage.
- The overall dataset has some missing values that were addressed via median or mode imputation.
""")

